{{- $scenario := .Values.scenario -}}
{{- $image := .Values.image -}}
{{- $scope := .Values.scope -}}
{{- $stats := .Values.stats -}}
{{ range $shipname, $ship := .Values.ships }}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
    name: {{ $shipname }}
    labels:
        scenario: {{ $scenario }}

spec:
    replicas: {{ $ship.replicas }}

    selector:
        matchLabels:
            scenario: {{ $scenario }}
            ship: {{ $shipname }}

    template:
        metadata:
            labels:
                scenario: {{ $scenario }}
                ship: {{ $shipname }}
        spec:
            terminationGracePeriodSeconds: 10
            shareProcessNamespace: true
            containers:
                - name: sensor
                  image: {{ $image | default "bottle:latest" }}
                  command: ["/bin/sh", "-c", "rpm -Uvh --nodeps sensor.rpm ; cd /usr/local/tet ; ./start_sensor.sh"]
                  volumeMounts:
                      - mountPath: /usr/local/tet
                        name: tet
                  securityContext:
                    capabilities:
                        add:
                            - SYS_PTRACE
                            - NET_ADMIN
                            - NET_RAW
                - name: enforcer
                  image: {{ $image | default "bottle:latest" }}
                  command: ["/bin/sh", "-c", "sleep 120; cd /usr/local/tet ; ./tet-enforcer --logtostderr"]
                  volumeMounts:
                      - mountPath: /usr/local/tet
                        name: tet
                  securityContext:
                    capabilities:
                        add:
                            - SYS_PTRACE
                            - NET_ADMIN
                            - NET_RAW
                - name: generator
                  image: {{ $image | default "bottle:latest" }}
                  env:
                    - name: BOTTLE_SCOPE
                      value: {{ $scope | default "Default"}}
                    - name: BOTTLE_SCENARIO
                      value: {{ $scenario }}
                    - name: BOTTLE_SHIP
                      value: {{ $shipname }}
                    - name: BOTTLE_STATS
                      value: {{ $stats | default "false" | toString | quote }}
                  volumeMounts:
                    - mountPath: /etc/ship
                      name: config
                    - mountPath: /usr/local/tet
                      name: tet
                  securityContext:
                    capabilities:
                        add:
                            - SYS_PTRACE
            volumes:
                - name: tet
                  emptyDir: {}
                - name: config
                  configMap:
                    name: {{ $scenario }}-config
                    items:
                        - key: {{ $shipname }}
                          path: conf.yaml
---
{{end}}